branches:
  only:
    - master
    - travis
language: ruby
rvm:
  - 2.3.1
script:
  - bundle exec danger
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
  webhooks:
    urls:
      - https://hooks.cybertail.systems/v1/62521B631763B4981AD8AE31822452F1FB48662790980CCF6D77E026D6328D81
