branches:
  only:
    - master
    - travis
language: ruby
rvm:
  - 2.3.1
script:
  - bundle exec danger
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
  webhooks:
    urls:
      - https://uplink-app.herokuapp.com/travis_hooks
